### PR TITLE
Fix faulty date validation in Lease

### LINKED ISSUE #130: Tests: Update test cases for Lease methods
Update test cases for these methods:
- toDisplayValue
- isValidLease

### LINKED ISSUE #168: Faulty date validation in Lease (dates that don't exist can be added)
Image

For example, February the 31st does not exist but can be added.

Image

### PR DESCRIPTION
**Pull request by yorick-chew**
- Fixes #168: Fix date validation for cases such as 29 Feb
- Fixes #130: Update test cases for lease

### CODE REVIEW

File: src/main/java/seedu/estatemate/model/person/Lease.java [hunk 1]
```diff
@@ -34,7 +36,7 @@ public class Lease {
     /**
      * Constructs a {@code Lease}.
      *
-     * @param lease A valid lease of format "yyyy-MM-dd yyyy-MM-dd".
+     * @param lease A valid lease of format "uuuu-MM-dd uuuu-MM-dd".
```
Comment (bearkerb) [inline src/main/java/seedu/estatemate/model/person/Lease.java]: Is there a reason to change it to uuuu here? yyyy seems like it would be more intuitive to me.

Comment (yorick-chew) [reply src/main/java/seedu/estatemate/model/person/Lease.java]: Thanks for clarifying with me. The resolver strict setting checks that the input has a valid era (AD or BC), so using uuuu accounts for the era.
