### PR TITLE
Fix PayDate to reject invalid calendar dates

### LINKED ISSUE #170: Date validation for paydate parameter in `tenant` command accepts invalid date
The add tenant command accepts invalid paydates such as `2026-02-30` or `2026-02-31` but appears to round it down to the nearest valid date `2026-02-28` after the tenant is added to the GUI.

For example, inputting the following command: `tenant n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 lease/2025-12-01 2027-02-01 r/1100.00 paydate/2026-02-31 t/friends t/owesMoney`

Image

The app creates the tenant but with the paydate set to `2026-02-28` which is a valid date.

Image

This could be confusing to users or cause problems when users mistakenly type in the invalid date and do not realise so.

### PR DESCRIPTION
**Pull request by michellee15**
Closes #170  #206

### CODE REVIEW

File: src/test/java/seedu/estatemate/model/person/PayDateTest.java [hunk 1]
```diff
@@ -23,6 +23,8 @@ public void construct_invalidPayDate_throwsIllegalArgumentException() {
         assertThrows(IllegalArgumentException.class, () -> new PayDate("2025-9-1"));
         assertThrows(IllegalArgumentException.class, () -> new PayDate("12-09-2025"));
         assertThrows(IllegalArgumentException.class, () -> new PayDate("2025.09.12"));
+        assertThrows(IllegalArgumentException.class, () -> new PayDate("2025-03-32"));
```
Comment (bearkerb) [inline src/test/java/seedu/estatemate/model/person/PayDateTest.java]: good on remembering to add tests and not just check for invalid dates in february regarding leap years
